version: '3'

services:
  # Database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - /home/deploy/stockmaster/.env
    environment:
      - POSTGRES_USER=stockmaster_admin
      - POSTGRES_PASSWORD=StockMaster2025!
      - POSTGRES_DB=stockmaster
    restart: always
    networks:
      - stockmaster_network

  # Redis for caching and Celery
  redis:
    image: redis:7
    restart: always
    networks:
      - stockmaster_network

  # Web application
  web:
    build: .
    restart: always
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - /home/deploy/stockmaster/.env
    depends_on:
      - db
      - redis
    command: >
      bash -c "python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - stockmaster_network

  # Celery worker
  celery:
    build: .
    restart: always
    volumes:
      - ./:/app
    env_file:
      - /home/deploy/stockmaster/.env
    depends_on:
      - db
      - redis
      - web
    command: celery -A config worker -l info
    networks:
      - stockmaster_network

  # Celery beat for periodic tasks
  celery-beat:
    build: .
    restart: always
    volumes:
      - ./:/app
    env_file:
      - /home/deploy/stockmaster/.env
    depends_on:
      - db
      - redis
      - web
    command: celery -A config beat -l info
    networks:
      - stockmaster_network

  # Nginx for serving web application
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/stockmaster.conf:/etc/nginx/conf.d/stockmaster.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - stockmaster_network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email aissa.chamtouri@gmail.com --agree-tos --no-eff-email -d cloud-549585597.onetsolutions.network --force-renewal
    networks:
      - stockmaster_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  stockmaster_network:
    driver: bridge 