# Generated by Django 4.2.7 on 2025-04-07 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(help_text='The myshopify.com domain of the store', max_length=255, unique=True)),
                ('shop_name', models.CharField(blank=True, help_text='The name of the store', max_length=255, null=True)),
                ('shop_email', models.EmailField(blank=True, help_text='The email of the store owner', max_length=254, null=True)),
                ('access_token', models.CharField(blank=True, help_text='The OAuth access token', max_length=255, null=True)),
                ('scope', models.TextField(blank=True, help_text='The scopes granted to the app', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the store is active')),
                ('plan', models.CharField(default='free', help_text='The subscription plan for the store', max_length=50)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends', null=True)),
                ('subscription_id', models.CharField(blank=True, help_text='The ID of the subscription in Shopify Billing', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, help_text='The last time the store accessed the app')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopify Store',
                'verbose_name_plural': 'Shopify Stores',
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(help_text='The ID of the webhook in Shopify', max_length=255)),
                ('topic', models.CharField(help_text='The webhook topic', max_length=100)),
                ('address', models.URLField(help_text='The webhook callback URL')),
                ('format', models.CharField(default='json', help_text='The format of the webhook', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='accounts.shopifystore')),
            ],
            options={
                'verbose_name': 'Shopify Webhook',
                'verbose_name_plural': 'Shopify Webhooks',
                'unique_together': {('store', 'webhook_id')},
            },
        ),
        migrations.AddIndex(
            model_name='shopifystore',
            index=models.Index(fields=['shop_url'], name='accounts_sh_shop_ur_52337b_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifystore',
            index=models.Index(fields=['is_active'], name='accounts_sh_is_acti_5263ff_idx'),
        ),
    ]
