# Generated by Django 4.2.8 on 2025-04-08 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rule description', null=True)),
                ('trigger_type', models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock'), ('back_in_stock', 'Back in Stock')], help_text='When the rule is triggered', max_length=50)),
                ('threshold', models.IntegerField(default=0, help_text='Threshold value for triggering the rule (e.g., 0 for out of stock)')),
                ('action_type', models.CharField(choices=[('hide_product', 'Hide Product'), ('show_product', 'Show Product'), ('move_to_collection', 'Move to Collection'), ('reorder_collection', 'Reorder in Collection'), ('tag_product', 'Tag Product'), ('notify', 'Send Notification')], help_text='The action to take', max_length=50)),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay in minutes before applying the action')),
                ('auto_restore', models.BooleanField(default=False, help_text='Whether to automatically restore the product')),
                ('restore_after_days', models.IntegerField(default=0, help_text='Days after which to restore the product')),
                ('product_type_filter', models.CharField(blank=True, help_text='Apply only to specific product types', max_length=255, null=True)),
                ('vendor_filter', models.CharField(blank=True, help_text='Apply only to specific vendors', max_length=255, null=True)),
                ('tag_filter', models.CharField(blank=True, help_text='Apply only to products with specific tags', max_length=255, null=True)),
                ('collection_filter', models.CharField(blank=True, help_text='Apply only to products in specific collections', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the rule is active')),
                ('priority', models.IntegerField(default=0, help_text='Rule priority (higher number = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.shopifystore')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='pending', help_text='Current status of the rule application', max_length=50)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the rule was triggered')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When the action is scheduled to be applied', null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the action was actually applied', null=True)),
                ('restore_scheduled_for', models.DateTimeField(blank=True, help_text='When the product is scheduled to be restored', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the rule application', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_applications', to='inventory.product')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rules.rule')),
            ],
            options={
                'verbose_name': 'Rule Application',
                'verbose_name_plural': 'Rule Applications',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['status'], name='rules_rulea_status_a9ed62_idx'), models.Index(fields=['scheduled_for'], name='rules_rulea_schedul_2934f3_idx'), models.Index(fields=['restore_scheduled_for'], name='rules_rulea_restore_cc229e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['store', 'is_active'], name='rules_rule_store_i_b8a218_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['store', 'trigger_type'], name='rules_rule_store_i_30213c_idx'),
        ),
    ]
